create table MANAGER
(
	ID       INT AUTO_INCREMENT NOT NULL,
	USERNAME VARCHAR(20) NOT NULL,
	PASSWORD VARCHAR(40) NOT NULL,
	PRIMARY KEY(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
insert into MANAGER (ID, USERNAME, PASSWORD) values (1, 'rjgc', 'rjgc');